"""
mongo_label_export.py
======================

Fetches documents from every MongoDB collection used by the "smriti-kunj"
backend, attaches the human-readable labels (title / description / unit /
domain) defined in SCHEMA_LABELLING_GUIDE.md, and writes everything to a
single "long format" CSV:

    collection | document_id | field_name | title | description | unit |
    domain | value | is_labelled

One row = one (document, field) pair. This format lets you open the CSV in
Excel/Sheets, filter by collection or domain, and see the raw value next to
its plain-English meaning -- instead of guessing what `avg_latency_ms` or
`r_squared` means from a bare export.

Fields that are NOT yet described in the guide are still exported (so no
data is silently dropped) but are flagged with is_labelled=False and a
generic humanized title, so you can spot gaps at a glance.

Usage
-----
    pip install pymongo

    # Option 1: environment variables
    export MONGO_URI="mongodb://localhost:27017"
    export MONGO_DB="cognitive_assist"
    python mongo_label_export.py

    # Option 2: command-line flags (override env vars)
    python mongo_label_export.py --uri "mongodb+srv://user:pass@cluster/" \
                                  --db cognitive_assist \
                                  --out labelled_export.csv \
                                  --collections game_sessions drift_metrics

No code in the actual backend repo is touched -- this is a standalone,
read-only export tool.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import sys
from datetime import datetime, date
from typing import Any, Dict, Iterable, List, Optional

try:
    from pymongo import MongoClient
except ImportError:
    sys.exit(
        "pymongo is not installed. Run:\n\n    pip install pymongo\n"
    )


# --------------------------------------------------------------------------
# 1. LABEL MAP
#    Transcribed directly from SCHEMA_LABELLING_GUIDE.md (sections 2 and 4).
#    Keyed by MongoDB collection name -> field name -> label metadata.
#    Extend this dict as more fields get labelled in the guide/codebase.
# --------------------------------------------------------------------------

LABEL_MAP: Dict[str, Dict[str, Dict[str, str]]] = {

    # --- game_sessions ----------------------------------------------------
    "game_sessions": {
        "session_id": {"title": "Session UUID", "description": "Unique session identifier"},
        "patient_profile_id": {"title": "Patient Profile ID", "description": "ID of patient who completed the session"},
        "patient_id": {"title": "Patient ID", "description": "Target patient UUID referencing the users collection"},
        "client_session_id": {"title": "Client Session ID", "description": "Idempotency key generated by the edge tablet to prevent duplicate syncs"},
        "game_type": {"title": "Game Identifier", "description": "Specific cognitive game module played (e.g. pattern_matcher, pair_matching, word_association, visual_search)"},
        "domain": {"title": "Cognitive Domain", "description": "Primary cognitive function targeted (memory, language, attention)"},
        "session_date": {"title": "Session Date", "description": "Date the session took place"},
        "session_duration": {"title": "Session Duration", "description": "Total elapsed playing time", "unit": "seconds"},
        "status": {"title": "Completion Status", "description": "Whether the game was completed or abandoned"},
        "difficulty_level": {"title": "Difficulty Tier", "description": "Difficulty configuration level or grid size"},
        "score_normalized": {"title": "Normalized Score", "description": "Adjusted score scaled 0.0-100.0 based on the difficulty algorithm"},
        "accuracy": {"title": "Accuracy Rate", "description": "Proportion of correct actions to total actions (0.0-1.0)"},
        "avg_latency_ms": {"title": "Average Latency", "description": "Average response time per user interaction", "unit": "ms"},
        "error_rate": {"title": "Error Rate", "description": "Ratio of incorrect responses or omissions (0.0-1.0)"},
        "client_timestamp": {"title": "Local Completion Timestamp", "description": "UTC datetime when the session was completed locally on the tablet"},
        "synced_at": {"title": "Sync Timestamp", "description": "Server ingestion timestamp"},
        "raw_payload": {"title": "Raw Telemetry Payload", "description": "Detailed interaction trial logs, touches, and timing vectors"},
        # Domain 1: Memory (pair matching)
        "correct_match_rate": {"title": "Correct Match Rate", "description": "Ratio of successful pairs found per card flip attempt (0.0-1.0)", "domain": "memory"},
        "total_flips": {"title": "Total Card Flips", "description": "Total individual card flip interactions during the round", "domain": "memory"},
        "time_to_first_correct_match": {"title": "Latency to First Match", "description": "Elapsed time before discovering the first matching pair", "unit": "seconds", "domain": "memory"},
        "repeat_error_rate": {"title": "Perseverative Error Rate", "description": "Frequency of re-flipping previously revealed non-matching cards (0.0-1.0)", "domain": "memory"},
        "completion_time": {"title": "Board Completion Time", "description": "Total time taken to clear the board", "unit": "seconds", "domain": "memory"},
        "pairs_count": {"title": "Total Pairs Count", "description": "Number of matching pairs on the game board", "domain": "memory"},
        "used_face_name_variant": {"title": "Face-Name Variant Used", "description": "True if patient's family photos were used instead of generic icons", "domain": "memory"},
        # Domain 2: Language (word association)
        "words_recalled_count": {"title": "Recalled Words Count", "description": "Total valid verbal or typed responses provided", "domain": "language"},
        "response_latency_per_word": {"title": "Per-Word Latencies", "description": "Array of response delays for each recalled item", "unit": "seconds", "domain": "language"},
        "category_switch_errors": {"title": "Category Switch Errors", "description": "Number of out-of-category or perseverative language errors", "domain": "language"},
        "language_used": {"title": "Language Used", "description": "Language used for the verbal or text prompt (ISO 639-1, e.g. bn, en)", "domain": "language"},
        "category_prompt": {"title": "Prompt Category", "description": "Stimulus category presented to the patient", "domain": "language"},
        "round_duration": {"title": "Round Duration Limit", "description": "Configured countdown duration for the round", "unit": "seconds", "domain": "language"},
        # Domain 3: Attention (visual search)
        "reaction_time_avg": {"title": "Average Target Reaction Time", "description": "Mean reaction time when selecting valid targets", "unit": "ms", "domain": "attention"},
        "reaction_time_variability": {"title": "Reaction Time Variance", "description": "Std. deviation of reaction times across trials (attention stability)", "unit": "ms", "domain": "attention"},
        "omission_rate": {"title": "Omission Error Rate", "description": "Rate of target stimuli missed without a response (0.0-1.0)", "domain": "attention"},
        "false_positive_rate": {"title": "False Positive Rate", "description": "Rate of selecting distractors instead of true targets (0.0-1.0)", "domain": "attention"},
        "within_session_drift": {"title": "Intra-Session Vigilance Drift", "description": "Fatigue indicator: slope of latency degradation from start to end of session", "domain": "attention"},
        "trial_count": {"title": "Total Trials Count", "description": "Number of stimulus presentations in the visual search session", "domain": "attention"},
        "raw_trials": {"title": "Raw Trial Records", "description": "Granular trial-by-trial logs with coordinate and timing metadata", "domain": "attention"},
    },

    # --- drift_metrics ------------------------------------------------------
    "drift_metrics": {
        "patient_id": {"title": "Patient ID", "description": "Target patient UUID"},
        "window_days": {"title": "Evaluation Window", "description": "Rolling observation window duration (typically 7 or 30 days)", "unit": "days"},
        "slope": {"title": "Regression Slope (Beta 1)", "description": "Cognitive trajectory slope; negative = decline, near-zero = stability"},
        "intercept": {"title": "Regression Intercept (Beta 0)", "description": "Baseline performance score estimate at the start of the window"},
        "r_squared": {"title": "Coefficient of Determination (R\u00b2)", "description": "Goodness-of-fit of the linear regression trend (0.0-1.0)"},
        "sample_count": {"title": "Sample Count", "description": "Total number of game sessions analyzed within this window"},
        "computed_at": {"title": "Computation Timestamp", "description": "UTC timestamp when the drift regression analysis was computed"},
    },

    # --- alerts ---------------------------------------------------------
    "alerts": {
        "patient_id": {"title": "Patient ID", "description": "Patient the alert was generated for"},
        "alert_type": {"title": "Alert Type", "description": "Category of alert (e.g. cognitive_drift, anomaly, missed_routine)"},
        "severity": {"title": "Severity Level", "description": "Triaged priority level of the notification (low, medium, high)"},
        "message": {"title": "Alert Message", "description": "Human-readable notification text displayed on the caregiver portal"},
        "resolved": {"title": "Resolution Status", "description": "Whether a caregiver has acknowledged and resolved the alert"},
        "created_at": {"title": "Creation Timestamp", "description": "UTC timestamp when the alert event was triggered"},
    },

    # --- voice_interactions ----------------------------------------------
    "voice_interactions": {
        "client_session_id": {"title": "Client Interaction ID", "description": "Idempotency UUID for the voice exchange"},
        "patient_id": {"title": "Patient ID", "description": "Patient who recorded the voice check-in"},
        "transcript": {"title": "Speech Transcript", "description": "Recognized text transcribed on-device by edge speech-to-text"},
        "language": {"title": "Language Code", "description": "BCP-47 / ISO-639-1 language identifier (bn, as, mni, en)"},
        "client_timestamp": {"title": "Local Timestamp", "description": "UTC datetime when the voice check-in occurred"},
        "synced_at": {"title": "Sync Timestamp", "description": "Server ingestion timestamp"},
    },

    # --- family_members -----------------------------------------------------
    "family_members": {
        "patient_id": {"title": "Patient ID", "description": "Patient this family member is linked to"},
        "name": {"title": "Full Name", "description": "Full name of family member"},
        "relation": {"title": "Relationship", "description": "Relationship to patient"},
        "photoUrl": {"title": "Photo URL", "description": "Photo data URI or URL"},
    },

    # --- patient_reminders ------------------------------------------------
    "patient_reminders": {
        "patient_id": {"title": "Patient ID", "description": "Patient this reminder belongs to"},
        "title": {"title": "Reminder Title", "description": "Short label for the reminder shown to the patient"},
        "time": {"title": "Scheduled Time", "description": "Time of day the reminder should trigger"},
        "recurrence": {"title": "Recurrence Rule", "description": "How often the reminder repeats (e.g. daily, weekly)"},
        "active": {"title": "Active Status", "description": "Whether the reminder is currently enabled"},
    },

    # --- users --------------------------------------------------------------
    "users": {
        "role": {"title": "User Role", "description": "Allowable persona for the account (caregiver, patient)"},
        "region_language": {"title": "Region Language", "description": "ISO 639-1 language code (bn=Bengali, as=Assamese, mni=Meitei)"},
        "phone": {"title": "Phone Number", "description": "Registered phone number for login / OTP delivery"},
        "name": {"title": "Full Name", "description": "User's full name"},
        "created_at": {"title": "Account Created", "description": "UTC timestamp the account was created"},
    },

    # --- otp_codes ------------------------------------------------------
    "otp_codes": {
        "otp": {"title": "One-Time Passcode", "description": "Ephemeral one-time numeric passcode used for 2FA"},
        "phone": {"title": "Phone Number", "description": "Phone number the OTP was issued to"},
        "expires_at": {"title": "Expiry Timestamp", "description": "UTC time after which the OTP is no longer valid"},
    },

    # --- device_pairing_tokens ------------------------------------------
    "device_pairing_tokens": {
        "pairing_token": {"title": "Pairing Token", "description": "One-time token used to bond a tablet to a patient profile"},
        "pairing_code": {"title": "Pairing Code", "description": "Short human-enterable code shown during device pairing"},
        "patient_id": {"title": "Patient ID", "description": "Patient the pairing token was issued for"},
        "expires_at": {"title": "Expiry Timestamp", "description": "UTC time after which the pairing token is no longer valid"},
    },

    # --- revoked_tokens ---------------------------------------------------
    "revoked_tokens": {
        "token": {"title": "Revoked Token", "description": "JWT or session token that has been invalidated"},
        "revoked_at": {"title": "Revocation Timestamp", "description": "UTC time the token was revoked"},
    },

    # --- bandit_arm_state -------------------------------------------------
    "bandit_arm_state": {
        "patient_id": {"title": "Patient ID", "description": "Patient this multi-armed-bandit state belongs to"},
        "arm_id": {"title": "Arm ID", "description": "Identifier of the bandit arm (e.g. a specific game/difficulty variant)"},
        "reward_estimate": {"title": "Reward Estimate", "description": "Current estimated reward value for this arm"},
        "pull_count": {"title": "Pull Count", "description": "Number of times this arm has been selected"},
    },
}

# Fields that are common/generic enough to label the same way everywhere.
GLOBAL_LABELS: Dict[str, Dict[str, str]] = {
    "_id": {"title": "Document ID", "description": "MongoDB primary key (ObjectId or binary UUID)"},
    "id": {"title": "Record ID", "description": "Unique identifier for this record"},
}


# --------------------------------------------------------------------------
# 2. Helpers
# --------------------------------------------------------------------------

def humanize(field_name: str) -> str:
    """Fallback title generator for fields not yet in the guide."""
    words = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", field_name)   # camelCase -> camel Case
    words = words.replace("_", " ")
    return words.strip().title()


def get_label(collection: str, field: str) -> Dict[str, str]:
    meta = LABEL_MAP.get(collection, {}).get(field)
    if meta is None:
        meta = GLOBAL_LABELS.get(field)
    if meta:
        return {
            "title": meta.get("title", humanize(field)),
            "description": meta.get("description", ""),
            "unit": meta.get("unit", ""),
            "domain": meta.get("domain", ""),
            "is_labelled": True,
        }
    return {
        "title": humanize(field),
        "description": "No description available yet -- add this field to LABEL_MAP / the guide.",
        "unit": "",
        "domain": "",
        "is_labelled": False,
    }


def serialize_value(value: Any) -> str:
    """Turn any BSON/Python value into a CSV-safe string."""
    if value is None:
        return ""
    if isinstance(value, (datetime, date)):
        return value.isoformat()
    if isinstance(value, (dict, list)):
        try:
            return json.dumps(value, default=str, ensure_ascii=False)
        except TypeError:
            return str(value)
    return str(value)


def flatten_document(doc: Dict[str, Any]) -> Dict[str, Any]:
    """MongoDB documents are usually already flat enough; nested dicts/lists
    are kept intact and JSON-serialized as a single field value rather than
    exploded into many columns, so each row still maps to one labelled field."""
    return doc


# --------------------------------------------------------------------------
# 3. Core export logic
# --------------------------------------------------------------------------

DEFAULT_COLLECTIONS = [
    "users",
    "device_pairing_tokens",
    "otp_codes",
    "revoked_tokens",
    "game_sessions",
    "voice_interactions",
    "drift_metrics",
    "alerts",
    "bandit_arm_state",
    "family_members",
    "patient_reminders",
]

CSV_COLUMNS = [
    "collection",
    "document_id",
    "field_name",
    "title",
    "description",
    "unit",
    "domain",
    "value",
    "is_labelled",
]


def export_to_csv(
    uri: str,
    db_name: str,
    collections: Iterable[str],
    out_path: str,
    limit: Optional[int] = None,
) -> Dict[str, int]:
    client = MongoClient(uri, serverSelectionTimeoutMS=8000)
    db = client[db_name]

    stats: Dict[str, int] = {}

    with open(out_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=CSV_COLUMNS)
        writer.writeheader()

        for coll_name in collections:
            if coll_name not in db.list_collection_names():
                print(f"[skip] '{coll_name}' does not exist in database '{db_name}'")
                stats[coll_name] = 0
                continue

            cursor = db[coll_name].find({}, limit=limit) if limit else db[coll_name].find({})
            row_count = 0

            for doc in cursor:
                doc = flatten_document(doc)
                document_id = serialize_value(doc.get("_id", ""))

                for field_name, value in doc.items():
                    label = get_label(coll_name, field_name)
                    writer.writerow({
                        "collection": coll_name,
                        "document_id": document_id,
                        "field_name": field_name,
                        "title": label["title"],
                        "description": label["description"],
                        "unit": label["unit"],
                        "domain": label["domain"],
                        "value": serialize_value(value),
                        "is_labelled": label["is_labelled"],
                    })
                    row_count += 1

            stats[coll_name] = row_count
            print(f"[ok] {coll_name}: exported {row_count} labelled field-rows")

    client.close()
    return stats


# --------------------------------------------------------------------------
# 4. CLI
# --------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Fetch MongoDB data, attach schema-guide labels, export to CSV."
    )
    parser.add_argument(
        "--uri",
        default=os.environ.get("MONGO_URI", "mongodb://localhost:27017"),
        help="MongoDB connection URI (default: $MONGO_URI or mongodb://localhost:27017)",
    )
    parser.add_argument(
        "--db",
        default=os.environ.get("MONGO_DB", "cognitive_assist"),
        help="Database name (default: $MONGO_DB or 'cognitive_assist')",
    )
    parser.add_argument(
        "--collections",
        nargs="*",
        default=DEFAULT_COLLECTIONS,
        help="Specific collections to export (default: all known collections)",
    )
    parser.add_argument(
        "--out",
        default="labelled_export.csv",
        help="Output CSV file path (default: labelled_export.csv)",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Optional max number of documents per collection (useful for a quick sample run)",
    )
    args = parser.parse_args()

    print(f"Connecting to {args.db} @ {args.uri} ...")
    stats = export_to_csv(args.uri, args.db, args.collections, args.out, args.limit)

    total_rows = sum(stats.values())
    print("\nSummary:")
    for coll, count in stats.items():
        print(f"  {coll:<22} {count} field-rows")
    print(f"\nWrote {total_rows} total rows to {args.out}")


if __name__ == "__main__":
    main()
    